// Generated by gencpp from file novatel_gps_msgs/NovatelPsrdop2System.msg
// DO NOT EDIT!


#ifndef NOVATEL_GPS_MSGS_MESSAGE_NOVATELPSRDOP2SYSTEM_H
#define NOVATEL_GPS_MSGS_MESSAGE_NOVATELPSRDOP2SYSTEM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace novatel_gps_msgs
{
template <class ContainerAllocator>
struct NovatelPsrdop2System_
{
  typedef NovatelPsrdop2System_<ContainerAllocator> Type;

  NovatelPsrdop2System_()
    : system()
    , tdop(0.0)  {
    }
  NovatelPsrdop2System_(const ContainerAllocator& _alloc)
    : system(_alloc)
    , tdop(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _system_type;
  _system_type system;

   typedef float _tdop_type;
  _tdop_type tdop;





  typedef boost::shared_ptr< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> const> ConstPtr;

}; // struct NovatelPsrdop2System_

typedef ::novatel_gps_msgs::NovatelPsrdop2System_<std::allocator<void> > NovatelPsrdop2System;

typedef boost::shared_ptr< ::novatel_gps_msgs::NovatelPsrdop2System > NovatelPsrdop2SystemPtr;
typedef boost::shared_ptr< ::novatel_gps_msgs::NovatelPsrdop2System const> NovatelPsrdop2SystemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator1> & lhs, const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator2> & rhs)
{
  return lhs.system == rhs.system &&
    lhs.tdop == rhs.tdop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator1> & lhs, const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_gps_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59dbc686e7d2261c67fc353e8280db4b";
  }

  static const char* value(const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59dbc686e7d2261cULL;
  static const uint64_t static_value2 = 0x67fc353e8280db4bULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_gps_msgs/NovatelPsrdop2System";
  }

  static const char* value(const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GNSS System information provided by PSRDOP2 logs\n"
"string system\n"
"float32 tdop\n"
;
  }

  static const char* value(const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.system);
      stream.next(m.tdop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NovatelPsrdop2System_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_gps_msgs::NovatelPsrdop2System_<ContainerAllocator>& v)
  {
    s << indent << "system: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.system);
    s << indent << "tdop: ";
    Printer<float>::stream(s, indent + "  ", v.tdop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_GPS_MSGS_MESSAGE_NOVATELPSRDOP2SYSTEM_H
